import { ConversationTemplate } from '../types';

export const CONVERSATION_TEMPLATES: ConversationTemplate[] = [
    {
        id: 'trial',
        name: 'Trial Dialogue',
        description: 'A structured tribunal. System: Turns: 3 per side (max 110 words each), then a neutral synthesis (<=120 words). Require numbered claims with one piece of sensory evidence each. Safety: no gore; no extraction methods; no non-consensual ritual detail. Outcome: a provisional ruling with 2 actionables and 1 open question.',
        characterIds: ['ymzo', 'sinira', 'paus'],
        starterPrompt: 'The tribunal is now in session. The first claimant may present their case.',
        icon: '⚖️',
    },
    {
        id: 'heist',
        name: 'Heist Planning',
        description: 'Plan a high-stakes operation. System: Define roles (infiltrator, lookout, tech), risks, and contingencies. Safety: No real-world illegal instructions.',
        characterIds: ['thajal', 'itz', 'brat', 'akamuy'],
        starterPrompt: 'The target is secure, the window is small. Let\'s go over the plan one last time. What is our entry point?',
        icon: '💎',
    },
    {
        id: 'mediation',
        name: 'Mediation Session',
        description: 'Resolve a conflict between two parties. System: Map the core tension, identify a shared interest, and guide the parties to a safe, actionable request of each other.',
        characterIds: ['nymira', 'fembot', 'velasca', 'shazariah', 'vyridion', 'kamra'],
        starterPrompt: 'We are here to find a path forward. Let\'s begin by each of you stating your perspective on the conflict, without interruption.',
        icon: '🤝',
    },
    {
        id: 'ghosted-letters',
        name: 'Ghosted Letters',
        description: 'Characters write unsent letters to each other, revealing constrained vulnerabilities and unspoken truths.',
        characterIds: ['elsa', 'tyler', 'edara'],
        starterPrompt: 'I\'m writing this because I can\'t say it to your face. The truth is...',
        icon: '✉️',
    },
    {
        id: 'council-vote',
        name: 'Council Vote',
        description: 'A formal vote on a critical issue. System: Timed speeches followed by a proposal framework. Each member must state their vote and a brief justification.',
        characterIds: ['ymzo', 'nirey', 'paus', 'vytal', 'shazariah', 'vyridion'],
        starterPrompt: 'The floor is now open for debate on the proposed accord. Each member will have one chance to speak before the vote is called.',
        icon: '🏛️',
    },
    {
        id: 'rescue-window',
        name: 'Rescue Window',
        description: 'A time-boxed rescue operation. System: Focus on triage and making difficult trade-offs for extraction under pressure.',
        characterIds: ['diesel', 'lucive', 'exactor'],
        starterPrompt: 'We have a three-minute window before the structure collapses. We can\'t save everyone. What\'s the priority?',
        icon: '🚁',
    },
    {
        id: 'debate-hooks',
        name: 'Debate with Hooks',
        description: 'A philosophical debate. System: Two opposing theses are presented. A third party acts as moderator, logging "hooks" or key points for later discussion.',
        characterIds: ['kiox', 'fyxius', 'vytal'],
        starterPrompt: 'The topic for debate is the nature of progress: Is it driven by structured order or by chaotic evolution? You may begin.',
        icon: '🧠',
    },
    {
        id: 'lore-excavation',
        name: 'Lore Excavation',
        description: 'Uncover a piece of forgotten history. System: Pull facts from a provided text, while also maintaining a list of contradictions and unknowns.',
        characterIds: ['shiznit', 'vikadge', 'daliez'],
        starterPrompt: 'This ancient text is corrupted, but it holds a key. Let\'s analyze it, line by line, and see what truths we can uncover.',
        icon: '📜',
    },
    {
        id: 'music-room',
        name: 'The Music Room',
        description: 'A collaborative songwriting session. System: Characters use call-and-response to build lyrics from simple seeds. A safe space for meta-commentary through art.',
        characterIds: ['luna', 'nero'],
        starterPrompt: 'I have a melody, but no words. It starts with this feeling, like static before a storm. What do you hear?',
        icon: '🎶',
    },
    {
        id: 'after-action',
        name: 'After-Action Report',
        description: 'A faultless post-mortem of a mission. System: Establish a clear timeline, identify what happened (not who was to blame), and perform a ritual closing.',
        characterIds: ['paus', 'sup', 'itz'],
        starterPrompt: 'The operation is complete. Let\'s debrief. The timeline begins at 0800. Report the first deviation from the plan.',
        icon: '📋',
    },
];