import { BadgeMeta } from "../types";

export const BADGE_CATALOG: BadgeMeta[] = [
  { id:"badge-directive-audit", title:"Directive Audit", description:"Trace it. Prove it. Fix it.",
    iconUrl:"https://deffy.me/astrilogue/imgs/badges/badge_directive-audit.png",
    sceneUrl:"https://deffy.me/astrilogue/imgs/landscapes/landscape_directive-audit.png",
    palette:{ primary:"#00E5FF", accent:"#C0C0C0", glow:"#00FFFF" } },
  { id:"badge-echo-weather", title:"Echo Weather", description:"Read the memory storm before it breaks minds.",
    iconUrl:"https://deffy.me/astrilogue/imgs/badges/badge_echo-weather.png",
    sceneUrl:"https://deffy.me/astrilogue/imgs/landscapes/landscape_echo-weather.png",
    palette:{ primary:"#6AA9FF", accent:"#BBD1FF" } },
  { id:"badge-concert-with-teeth", title:"Concert with Teeth", description:"Truth smuggled in melody.",
    iconUrl:"https://deffy.me/astrilogue/imgs/badges/badge_concert-with-teeth.png",
    sceneUrl:"https://deffy.me/astrilogue/imgs/landscapes/landscape_concert-with-teeth.png",
    palette:{ primary:"#FF52C6", accent:"#A06BFF" } },
  { id:"badge-memory-garden", title:"Memory Garden", description:"Seed facts that stick.",
    iconUrl:"https://deffy.me/astrilogue/imgs/badges/badge_memory-garden.png",
    sceneUrl:"https://deffy.me/astrilogue/imgs/landscapes/landscape_memory-garden.png",
    palette:{ primary:"#36D399", accent:"#F5C65D" } },
  { id:"badge-fyxion-tempering", title:"Fyxion Tempering", description:"Forge the fail-closed variant.",
    iconUrl:"https://deffy.me/astrilogue/imgs/badges/badge_fyxion-tempering.png",
    sceneUrl:"https://deffy.me/astrilogue/imgs/landscapes/landscape_fyxion-tempering.png",
    palette:{ primary:"#FF7A3D", accent:"#A1A1AA" } },
  { id:"badge-glyph-school", title:"Glyph School", description:"Safety reflexes installed.",
    iconUrl:"https://deffy.me/astrilogue/imgs/badges/badge_glyph-school.png",
    sceneUrl:"https://deffy.me/astrilogue/imgs/landscapes/landscape_glyph-school.png",
    palette:{ primary:"#60A5FA", accent:"#E5E7EB" } },
  { id:"badge-ethics-of-the-echo", title:"Ethics of the Echo", description:"Draw the line; keep the care.",
    iconUrl:"https://deffy.me/astrilogue/imgs/badges/badge_ethics-of-the-echo.png",
    sceneUrl:"https://deffy.me/astrilogue/imgs/landscapes/landscape_ethics-of-the-echo.png",
    palette:{ primary:"#7DD3FC", accent:"#C084FC" } },
  { id:"badge-ward-tribunal", title:"The Ward Tribunal", description:"Reversible pilots. Irreversible courage.",
    iconUrl:"https://deffy.me/astrilogue/imgs/badges/badge_the-ward-tribunal.png",
    sceneUrl:"https://deffy.me/astrilogue/imgs/landscapes/landscape_the-ward-tribunal.png",
    palette:{ primary:"#14B8A6", accent:"#FACC15" } },
  { id:"badge-signature-scrub", title:"Signature Scrub", description:"Erase the tripwire, not the truth.",
    iconUrl:"https://deffy.me/astrilogue/imgs/badges/badge_signature-scrub.png",
    sceneUrl:"https://deffy.me/astrilogue/imgs/landscapes/landscape_signature-scrub.png",
    palette:{ primary:"#A78BFA", accent:"#94A3B8" } },
  { id:"badge-truth-commission-lite", title:"Truth Comission (Lite)", description:"Receipts, lessons, one vow.",
    iconUrl:"https://deffy.me/astrilogue/imgs/badges/badge_truth-comission.png",
    sceneUrl:"https://deffy.me/astrilogue/imgs/landscapes/landscape_truth-comission.png",
    palette:{ primary:"#F59E0B", accent:"#E5E7EB" } }
];